services:
  - type: worker
    name: king-m-bot
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: king-m-db
          property: connectionString

databases:
  - name: king-m-db
    databaseName: kingdb
    user: kinguser
